### ISSUE TITLE
How to treat replicates for WT or KO?

### ISSUE THREAD

**Issue by nroak** [hoffmangroup/peako#1]
I have 2 replicates each for WT and KO conditions. I was wondering if the BAM files for each replicate need to run in separate commands or can they be run together?

**Comment by cviner** [comment]
Thanks for using peaKO!

You will need to either run the replicates individually or combine them yourself, prior to input into peaKO. As outlined in the "Combining replicates" section of our [paper](https://doi.org/10.1101/721720), we used IDR, within the [ENCODE pipeline](https://github.com/ENCODE-DCC/chip-seq-pipeline2), to combine replicates. This functionality, however, is not incorporated into peaKO.

Unless you are comparing pipelines or need a single combined replicate for particular biological reasons, running peaKO individually across replicates is likely sufficient.
